### ISSUE TITLE
wrapper needed. lose magic numbers.

### ISSUE THREAD

**Issue by ShayRubach** [RoeiRubach/Pong-game-Final-project#3]
https://github.com/RoeiRubach/Pong-game-Final-project/blob/46016c18213ebaac2a126935baa548c35132aab6/ConsoleAppPongFinalProject/ConsoleAppPongFinalProject/GameManager.cs#L52-L61

- move this block into separated function. for exmaple 'GetUserChoice()'
- lose the magic numbers (1,2) and use appropriate names (we like enums).
e.g 'Single Player' and 'Multiplayer'

**Comment by RoeiRubach** [comment]
Edited by adding an enum and losing the magic numbers.
