### ISSUE TITLE
Magic, magic everywhere.

### ISSUE THREAD

**Issue by ShayRubach** [RoeiRubach/Pong-game-Final-project#4]
https://github.com/RoeiRubach/Pong-game-Final-project/blob/46016c18213ebaac2a126935baa548c35132aab6/ConsoleAppPongFinalProject/ConsoleAppPongFinalProject/GameManager.cs#L268-L276

Again, magic numbers. Use meaningful enums instead

**Comment by RoeiRubach** [comment]
Edited by creating an enum, adding another method to check which part collided with the ball and placing it in the IsCollidedWithAnObject() method.
