### ISSUE TITLE
turn into function.

### ISSUE THREAD

**Issue by ShayRubach** [RoeiRubach/Pong-game-Final-project#5]
https://github.com/RoeiRubach/Pong-game-Final-project/blob/46016c18213ebaac2a126935baa548c35132aab6/ConsoleAppPongFinalProject/ConsoleAppPongFinalProject/GameManager.cs#L142-L153

could this be turned into function? 
e.g CheckPlayerMode() - to identify manual \ auto player.

**Comment by RoeiRubach** [comment]
Edited by creating another method called ChecksWhoScored().
