### ISSUE TITLE
naming, oh, naming.

### ISSUE THREAD

**Issue by ShayRubach** [RoeiRubach/Pong-game-Final-project#6]
https://github.com/RoeiRubach/Pong-game-Final-project/blob/46016c18213ebaac2a126935baa548c35132aab6/ConsoleAppPongFinalProject/ConsoleAppPongFinalProject/GameManager.cs#L156

you better use something like:
public static readonly string EMPTY_PIXEL = ' ';

**Comment by RoeiRubach** [comment]
Done.
