### ISSUE TITLE
func it

### ISSUE THREAD

**Issue by ShayRubach** [RoeiRubach/Pong-game-Final-project#7]
https://github.com/RoeiRubach/Pong-game-Final-project/blob/46016c18213ebaac2a126935baa548c35132aab6/ConsoleAppPongFinalProject/ConsoleAppPongFinalProject/GameManager.cs#L158-L168

could this ugly block be a meaningful function? since 'ball' and 'autoplayer' are accessible within the class, funcin' them would be a bless.

**Comment by RoeiRubach** [comment]
The ugliness has disappeared and turned into a beautiful methods.
