### ISSUE TITLE
GameManager should not hold any ScoreBoard logic.

### ISSUE THREAD

**Issue by ShayRubach** [RoeiRubach/Pong-game-Final-project#8]
https://github.com/RoeiRubach/Pong-game-Final-project/blob/46016c18213ebaac2a126935baa548c35132aab6/ConsoleAppPongFinalProject/ConsoleAppPongFinalProject/GameManager.cs#L337-L349

Inside ScoreBoard class, make a Print() function that receives an int and than calls PrintOne/Two/Three depending on the parameter. you DONT let the GameManager class to perform logic for the ScoreBoard!
You should only perform scoreBoard.Print(1/2/3/4) from the GameManager and that's it. Move responsibilities downwards and not upwards. Smaller responsibilities - better code.

**Comment by RoeiRubach** [comment]
Learning how to write better code, is my goal.
Done.
