### ISSUE TITLE
magic, might magic.

### ISSUE THREAD

**Issue by ShayRubach** [RoeiRubach/Pong-game-Final-project#9]
https://github.com/RoeiRubach/Pong-game-Final-project/blob/46016c18213ebaac2a126935baa548c35132aab6/ConsoleAppPongFinalProject/ConsoleAppPongFinalProject/GameManager.cs#L375-L384

i hate this numbers. they mean nothing :(

**Comment by RoeiRubach** [comment]
I guess you're right, as always ;)
Created a new enum. Thanks!
Done.
